name: LDRPluginS
version: 1.1.6
main: andytxr.ldrplugins.LDRPluginS
api-version: 1.13
author: andytxr_

commands:
  albums:
    description: Mostra álbuns da Lana Del Rey.
    usage: /albums
  albums escolher:
    description: Escolher álbuns para escutar da Lana del Rey.
    usage: /albums escolher nomedoalbum
  bencao:
    description: Receber a benção de Lana.
    usage: /bencao
  randomlocal:
    description: Teleportar para lugar aleatorio.
    usage: /randomlocal



